services:
  backend:
    build:
      context: .
      dockerfile: aws/Dockerfile
    ports:
      - '9000:9000'
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - '4242:4242'
    depends_on:
      - backend
    restart: always
